=== RicardoSantom/2122_LMSGI_RicardoST/ud5/pruebaEX02_20210309_RicardoST/mapaestelar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT mapaEstelar (constelacion,estrella)>
<!ATTLIST mapaEstelar xmlns:xsi CDATA #IMPLIED
              xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT constelacion (#PCDATA|nombre|superficie|estrellas|objetos|colindantes|observacion)*>
<!ATTLIST constelacion
            nombreLatin CDATA #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT estrellas (asterismo,masBrillante)>
<!ATTLIST estrellas 
            numeroEstrellas CDATA #REQUIRED>
<!ELEMENT asterismo (#PCDATA)>
<!ELEMENT masBrillante (#PCDATA)>
<!ATTLIST masBrillante
            luminosidad CDATA #REQUIRED>
<!ELEMENT objetos (cumulos,nebulosas,galaxias,cuasares,lluviaMeteoros?)>
<!ELEMENT cumulos (#PCDATA)>
<!ELEMENT nebulosas (#PCDATA)>
<!ELEMENT galaxias (#PCDATA)>
<!ELEMENT cuasares (#PCDATA)>
<!ELEMENT lluviaMeteoros (nombre+)>
<!ELEMENT colindantes (#PCDATA)>
<!ELEMENT observacion (hemisferio,mes,hora)>
<!ELEMENT hemisferio (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT estrella (nombre,constelacion,distancia,luminosidad,temperatura,masa)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia
            medida CDATA #FIXED 'anyosLuz'>
<!ELEMENT luminosidad (#PCDATA)>
<!ATTLIST luminosidad
            medida CDATA  'soles'>
<!ELEMENT temperatura (#PCDATA)>
<!ATTLIST temperatura
            medida CDATA 'K'>
<!ELEMENT masa (#PCDATA)>
<!ATTLIST masa
            medida CDATA 'soles'>

=== RicardoSantom/2122_LMSGI_RicardoST/ud5/pruebaEX02_20210309_RicardoST/mapaestelar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapaEstelar SYSTEM "mapaEstelar.dtd">
<mapaEstelar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mapaEstelar.xsd">
    <constelacion nombreLatin="Ursa Maior">
        <nombre>La Osa Mayor</nombre>
        <superficie>1297.7</superficie>
        <estrellas numeroEstrellas="209">
            <asterismo>7</asterismo>
            <masBrillante luminosidad="108">Alioth</masBrillante>
        </estrellas>
        <objetos>
            <cumulos>false</cumulos>
            <nebulosas>false</nebulosas>
            <galaxias>false</galaxias>
            <cuasares>false</cuasares>
            <lluviaMeteoros>
                <nombre>Kappa Ursa Mayoridas</nombre>
                <nombre>Lambda Ursa Mayoridas</nombre>
                <nombre>Psi ursa Mayoridas</nombre>
                <nombre>Ursa Mayoridas de octubre</nombre>
            </lluviaMeteoros>
        </objetos>
        <colindantes>Bootes</colindantes>
        <colindantes>Camelopardalis</colindantes>
        <colindantes>Canes Venatici</colindantes>
        <colindantes>Draco</colindantes>
        <colindantes>Leo</colindantes>
        <colindantes>Leo Minor</colindantes>
        <colindantes>Lynx</colindantes>
        <observacion>
            <hemisferio>Norte</hemisferio>
            <mes>--04</mes>
            <hora>21:00:00</hora>
        </observacion>
    </constelacion>
    <estrella>
        <nombre>Alioth</nombre>
        <constelacion>Ursa Maior</constelacion>
        <distancia medida="anyosLuz">81</distancia>
        <luminosidad medida="soles">108</luminosidad>
        <temperatura medida="K">9400</temperatura>
        <masa medida="soles">3</masa>
    </estrella>
</mapaEstelar>
