<?xml version="1.0" encoding="UTF-8"?>
<!--
XML02.- Escribir un documento XML que almacene la siguiente información:
CONTINENTE PAÍS CAPITAL
EUROPA ALEMANIA BERLÍN
AMÉRICA ARGENTINA BUENOS AIRES
AMÉRICA BAHAMAS NASSAU
ASIA AFGANISTÁN KABUL
ASIA ARABIA SAUDITA RIAD
-->
<!DOCTYPE mundo[
    <!ELEMENT mundo (fila+)>
    <!ATTLIST mundo 
                xmlns:xsi CDATA #IMPLIED
              xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
    <!ELEMENT fila (continente*,pais*,capital*)>
    <!ELEMENT continente (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT capital (#PCDATA)>
]>
<mundo xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='02.xsd'>
    <fila>
        <continente>europa</continente>
        <pais>Alemania></pais>
        <capital>Berlín</capital>
    </fila>
    <fila>
        <continente>América</continente>
        <pais>Argentina</pais>
        <capital>Buenos Aires</capital>
    </fila>
     <fila>
        <continente>América</continente>
        <pais>Bahamas</pais>
        <capital>Nassau</capital>
    </fila>
     <fila>
        <continente>Asia</continente>
        <pais>Afganistán</pais>
        <capital>Kabul</capital>
    </fila>
     <fila>
        <continente>Asia</continente>
        <pais>Arabia Saudita</pais>
        <capital>Riad</capital>
    </fila>
</mundo>