<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="03.xsl" type="text/xsl"?>
<!DOCTYPE hechoshistoricos[
    <!ELEMENT hechoshistoricos (acontecimiento+)>
    <!ELEMENT acontecimiento (descripcion?,fecha?)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT fecha (dia+,mes+,anyo+)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT anyo (#PCDATA)>
]>
<hechoshistoricos>
    <acontecimiento>
        <descripcion>Se funda Youtube</descripcion>
        <fecha>
            <dia>15</dia>
            <mes>2</mes>
            <anyo>2005</anyo>
        </fecha>
    </acontecimiento>
    <acontecimiento>
        <descripcion>Se funda Google</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>9</mes>
            <anyo>1998</anyo>
        </fecha>
    </acontecimiento>
    <acontecimiento>
        <descripcion>Se funda Facebook</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>2</mes>
            <anyo>2004</anyo>
        </fecha>
    </acontecimiento>
</hechoshistoricos>   

