=== RicardoSantom/2122_LMSGI_RicardoST/EX02_20220324_RicardoSantiagoTome/tabla.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:annotation>
        <xs:appinfo>tabla.xsd EX02_20220324_RicardoSantiagoTome</xs:appinfo>
        <xs:documentation xml:lang="es">
            Este esquema valida un XML de una tabla peri√≥dica de elementos
        </xs:documentation>
        <xs:documentation xml:lang="en">
            this schema validates an XML from a periodic table elements
        </xs:documentation>
    </xs:annotation>
    <!--<xs:simpleType name="tipoPunto">
        <xs:restriction base="xs:decimal
    </xs:simpleType>-->
    <xs:element name="tabla_periodica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="atomo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="simbolo" type="xs:string"/>
                            <xs:element name="numero_atomico">
                                <xs:simpleType>
                                        <xs:restriction base="xs:positiveInteger">
                                            <xs:minInclusive value="1"/>
                                            <xs:maxInclusive value="118"/>
                                        </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="valencias" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="valencia" minOccurs="1" maxOccurs="6">
                                            <xs:simpleType>
                                                    <xs:restriction base="xs:integer">
                                                        <xs:minInclusive value="-3"/>
                                                        <xs:maxInclusive value="8"/>
                                                    </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="peso_atomico" type="xs:decimal"/>
                            <xs:element name="punto_ebu" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:float">
                                            <xs:attribute name="unidades">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:pattern value="[KC]"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="punto_fus" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:float">
                                            <xs:attribute name="unidades">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:pattern value="[KC]"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="densidad" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="valor">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:decimal"/>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="periodo">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:minInclusive value="1"/>
                                    <xs:maxInclusive value="7"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="grupo">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:minInclusive value="1"/>
                                    <xs:maxInclusive value="18"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="bloque" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RicardoSantom/2122_LMSGI_RicardoST/EX02_20220324_RicardoSantiagoTome/tabla.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tabla_periodica SYSTEM "tabla.dtd">
<tabla_periodica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tabla.xsd">
    <atomo periodo="1" grupo="1" bloque="s">
        <nombre>Hidrogeno</nombre>
        <simbolo>H</simbolo>
        <numero_atomico>1</numero_atomico>
        <valencias>
            <valencia>1</valencia>
        </valencias>
        <peso_atomico>1.00797</peso_atomico>
        <punto_ebu unidades="K">20.268</punto_ebu>
        <punto_fus unidades="K">14.025</punto_fus>
        <densidad valor="0.071"/>
    </atomo>
    <atomo periodo="5" grupo="8" bloque="d">
        <nombre>Rutenio</nombre>
        <simbolo>Ru</simbolo>
        <numero_atomico>44</numero_atomico>
        <valencias>
            <valencia>2</valencia>
            <valencia>3</valencia>
            <valencia>4</valencia>
            <valencia>6</valencia>
            <valencia>8</valencia>
        </valencias>
        <peso_atomico>101.07</peso_atomico>
        <punto_ebu unidades="C">4900</punto_ebu>
        <punto_fus unidades="C">2500</punto_fus>
        <densidad valor="12.2"/>
    </atomo>
    <atomo periodo="6" grupo="17" bloque="p">
        <nombre>Astato</nombre>
        <simbolo>At</simbolo>
        <numero_atomico>85</numero_atomico>
        <peso_atomico>85</peso_atomico>
        <punto_fus unidades="C">302</punto_fus>
    </atomo>
</tabla_periodica>
